### ISSUE TITLE
Pick A Header Photo

### ISSUE THREAD

**Issue by hshazly** [hariharan-devarajan/cluster2023#6]

**Comment by hariharan-devarajan** [comment]
I am guessing a header photo for SantaFe.

![image](https://user-images.githubusercontent.com/21210820/173896312-23acba97-9058-4708-8da9-86f30172245f.png)

**Comment by hshazly** [comment]
Nice! got it from google?

**Comment by hariharan-devarajan** [comment]
Yes we can add the source.

**Comment by hshazly** [comment]
Cool, go ahead then. I'll close this issue.

**Comment by hshazly** [comment]
Reopened until checking up the copy-rights

**Comment by hariharan-devarajan** [comment]
updated the header photo provided.
